### ISSUE TITLE
email regex could be better

### ISSUE THREAD

**Issue by axlf** [fergaldoyle/vue-form#1]
Hey,

I'm not happy with the email regex becuase it invalidates for example .media addresses.
Perhaps you could add a way to change the default regex through options, or improve the regex.

Found a good one at http://emailregex.com. Fair to say it invalidates .media, too. But it could be added easily.

I could do a PR with a new regex if you like. Perhaps you have a better idea solving this...

**Comment by fergaldoyle** [comment]
Better regexp added in latest release, validates .media

**Comment by axlf** [comment]
thanks - that was fast!
