### ISSUE TITLE
Allow access to validator parameters in field-messages

### ISSUE THREAD

**Issue by FloEdelmann** [fergaldoyle/vue-form#109]
E.g. for the `min="3"` validator, I'd like to get an error message like "Field value must be at least 3".

Since my `<field-messages>` often look the same (apart from those parametrized validator messages), I've put them into a component which gets the field name and form state as props. Unfortunately, there is no access to validator parameters (the `3` in the example above) from there.

Did I miss something? Otherwise, adding support for this would be nice!

**Comment by fergaldoyle** [comment]
You can now access validation attributes with the `$attrs` property, e.g.
```html
<field-messages class="form-control-feedback" v-if="formstate.bbb">
  <div>Success!</div>
  <div slot="minlength">Minimum allowed characters for this field is {{formstate.bbb.$attrs.minlength}}</div>
  <div slot="maxlength">Maximum allowed characters for this field is {{formstate.bbb.$attrs.maxlength}}</div>
  <div slot="required">Field is required</div>
</field-messages>
```

https://github.com/fergaldoyle/vue-form/releases/tag/4.8.1

**Comment by FloEdelmann** [comment]
Nice, thank you!
