### ISSUE TITLE
Display error message after getting a server response

### ISSUE THREAD

**Issue by timur-sh** [fergaldoyle/vue-form#111]
The aim is display the server validation error. How can I do this?

For example: 
The request was sent to server didn't pass a validation and error message was getting. I'd like to display that above validation message under the appropriate field.

How can I do this?

**Comment by wtho** [comment]
While the Promise has to call `resolve()` with a boolean, you can set other values right before you call `resolve()` and use those in the `field-messages`, e. g.:
```js
return new Promise((resolve, reject) => {
  fetch('https://httpbin.org/get').then(response => {
    this.fieldNameServerMsg = response.serverMsg;
    resolve(response.isValid);
  });
});
```
```html
<field-messages name="fieldName">
  <div slot="asyncError">{{fieldNameServerMsg}}</div>
</field-messages>
```

Hope this response did not come too late. Please close the issue if this resolved it.
