### ISSUE TITLE
Dependency on extend is locked down to 3.0.1

### ISSUE THREAD

**Issue by ConnorStroomberg** [fergaldoyle/vue-form#117]
vue-from has a fixed version dependency on  extend: 3.0.1

extend: 3.0.2 fixes a [know security issue](https://snyk.io/vuln/npm:extend:20180424).

Possible solutions:

use `extend: "^3.0.1"` or `extend: "3.0.2"`

**Comment by fergaldoyle** [comment]
Closed with 7319c15409e8a4b18c77d3b5603c6de068b57630
