### ISSUE TITLE
Any plans for $touched?

### ISSUE THREAD

**Issue by ajarti** [fergaldoyle/vue-form#12]
Hi, 

Firstly thanks for a killer library, nice work!  

I was wondering if you have any plans to add a $touched property.

Motivation, on validation you don't want to start screaming at the user too soon, so one needs the user to possibly blur before getting an error.  E.g. email, it will be dirty after the first keydown, but that does not mean it's wrong (yet), they should not be given an error until they are presumably finished, but still before they submit the form.  So $dirty & $submitted can't achieve that.

Very new to Vue, but If I get up to speed may attempt a pull request, but well beyond me at the moment.

Thanks again.

**Comment by nivv** [comment]
:+1:

**Comment by ajarti** [comment]
In a mad rush at the mo, so no time to learn pull requests, so sorry for posting diff, though it might help:

> 30a31
>             touchedClass = 'vf-touched',
150a152
>                     $touched: false,
221a224,227
>                     },
>                     setTouched: function () {
>                         state.$touched = true;
>                         Vue.util.addClass(el, touchedClass);
290a297
>                     $touched: false,
346a354,358
>                     setTouched: function () {
>                         state.$touched = true;
>                         self._vueForm.setTouched();
>                         Vue.util.addClass(el, touchedClass);
>                     },
449a462
>                 Vue.util.on(el, 'focus', this._vueFormCtrl.setTouched);

**Comment by fergaldoyle** [comment]
Thanks, added `$touched` and `$untouched`. It happens on `blur` rather than `focus`.

**Comment by lavezzi1** [comment]
Hello, @fergaldoyle @ajarti @nivv 

Just wondering why $touched doesn't work when I try to validate component. 

```
<div v-form-ctrl="model.instance" name="instance" required>
  <my-component :value.sync="model.name"></my-component>
</div>
```

It's just always untouched. Thanks for any help!

**Comment by kaleb** [comment]
@lavezzi1 it is probably because focus does not bubble... may need to change focus to be a capture phase event listener.
