### ISSUE TITLE
Surprised the default "pattern" validator is opinionated. Should it be?

### ISSUE THREAD

**Issue by scottadamsmith** [fergaldoyle/vue-form#123]
https://github.com/fergaldoyle/vue-form/blob/fd7dbfc5e0ecae296529665ff6b17d93e18c41c2/src/validators.js#L51

We have overrode the built-in pattern validation with a more generic equivalent:

```
'pattern': function (value, pattern) {
  patternRegExp = new RegExp(pattern);
  patternRegExp.test(value); 
}
```

I realize this would be a breaking change, but adding the start and end to the pattern limits what you can validate.

**Comment by fergaldoyle** [comment]
As far as I can recall, I did this because it follows the HTML5 pattern attribute spec. I.e. the pattern is anchored at the start and end of the input string.

https://stackoverflow.com/questions/9142208/should-i-use-and-in-html5-input-regex-pattern-validation

**Comment by scottadamsmith** [comment]
That's a fair point. I am fine with having to override this behavior then. Thanks for explaining!
