### ISSUE TITLE
When would one use the <field> component instead of the <validate> component?

### ISSUE THREAD

**Issue by scottadamsmith** [fergaldoyle/vue-form#124]
For some reason I feel like I found this answer somewhere at some point, but I have dug around and can't find anything. Can you provide guidance as to what situation someone would want to use the field component instead of the validate component? None of the examples use the field component and the only reason I know about it is from the documentation. I am hoping to better understand its use case to make sure I am utilizing everything I can from the library.

Thanks!

**Comment by fergaldoyle** [comment]
The 'field' component is used for fields which have no validation rules but where you want to use the auto label feature. Auto label creates a 'for' attribute on the label and matching "id' attribute on the form field. This is mainly for IE to explicitly connect the two elements together but also helps with accessibility and certain screen readers.

**Comment by scottadamsmith** [comment]
Got it, thanks!
