### ISSUE TITLE
Release v4.10.2 on npm

### ISSUE THREAD

**Issue by FloEdelmann** [fergaldoyle/vue-form#130]
You recently released version [4.10.2 on GitHub](https://github.com/fergaldoyle/vue-form/releases/tag/4.10.2). The version number in `package.json` was not updated though ([see the diff](https://github.com/fergaldoyle/vue-form/compare/4.10.1...4.10.2)), and neither was the new release published on npm.

Thus, the new version containing bugfixes can't easily be used as a dependency.

I think it would be best to create a new release (4.10.3) to keep the git tags, GitHub releases and npm releases in sync.

**Comment by fergaldoyle** [comment]
Thanks, I hadn't released in a while so forgot the steps!
