### ISSUE TITLE
You are setting a non-existent path "myform" on a vm instance. 

### ISSUE THREAD

**Issue by rdpascua** [fergaldoyle/vue-form#16]
Why am I getting this error? should I put myform inside the data options?

**Comment by fergaldoyle** [comment]
Yes, create an empty object on the VM which will hold form state. It can be named whatever you like. The name attribute of your form element should then have the same name.

**Comment by kvdmolen** [comment]
@fergaldoyle 
Wouldn't it be an option to set the variable in the directive?
Perhaps using
```js
Vue.prototype[formname] = {}
```
