### ISSUE TITLE
vue-form for custom components doesn't work for me

### ISSUE THREAD

**Issue by eele94** [fergaldoyle/vue-form#19]
The given example does not work and I can't get it worked with my own components.
Did I do it wrong or is this a common bug?

Thanks

`<span v-form-ctrl="report.dateStart" name="dateStart" required>
                <datepicker :value.sync="report.dateStart"></datepicker>
              </span>
              <span v-if="myform.dateStart.$error.required" class="help-block error">{{$lang.requiredField}}</span>
`

**Comment by jxiaox** [comment]
+1

**Comment by eele94** [comment]
jxiaox can you add a solution if you find something?

Thanks

**Comment by fergaldoyle** [comment]
The example had some ES6 so wouldn't run in all browsers, updated now:
https://github.com/fergaldoyle/vue-form/blob/master/example/custom-component.html

Does the `datepicker` component happen to create a default Date object even if the user doesn't choose a date?

**Comment by fergaldoyle** [comment]
Closing Vue 1 compatible version issues.
