### ISSUE TITLE
Array input name

### ISSUE THREAD

**Issue by Rikcon** [fergaldoyle/vue-form#25]
Hello, i have a problem, vue-form does not seem to support array input names ( like name="new_password[confirmation]" ).
Here is a screenshot of vue-devtools (new_password -> undefined). 
That undefined should be confirmation, or i'm mistaken ? 

Also it acts weird with validations on those undefined inputs.

![2016-05-17_14-27-30](https://cloud.githubusercontent.com/assets/1577550/15320935/f87b4372-1c3b-11e6-9c56-84a51271b5b1.png)

**Comment by fergaldoyle** [comment]
Closing Vue 1 compatible version issues.
