### ISSUE TITLE
How does this compare to vue-validator?

### ISSUE THREAD

**Issue by jakobrosenberg** [fergaldoyle/vue-form#29]
I'm trying to choose between vue-form and vue-validator. Can you tell me how they differ and what caused you to create a new solution?

**Comment by taoeffect** [comment]
I'm not the author but I can say why I chose vue-form:

- it's simpler and easier to use, vue-validator has a lot of unnecessary stuff in it
- this means less code to ship to client; snappier sites, etc

**Comment by fergaldoyle** [comment]
vue-validator is component based where as vue-form is directive based. 

I wanted something that used html5 input validation attributes, worked on custom input components and had similar behaviour to angular form validation, hence vue-form

**Comment by jakobrosenberg** [comment]
Thanks guys.
