### ISSUE TITLE
Can I validate again after the data was posted?

### ISSUE THREAD

**Issue by exoticknight** [fergaldoyle/vue-form#30]
I need to post data first to check whether the data exist. If exist, I will know the id of that 'input'
so I tried to do sth like this

``` javascript
ajax.post({data}, (res)=>{
  Vue.set(validation.$error[res.id].only, true)
})
```

mean while in HTML

``` html
<span v-if="validation.$error.[id].only">existed</span>
```

but failed
or may be I just did the wrong way?

**Comment by fergaldoyle** [comment]
Closing Vue 1 compatible version issues. Async validators work in version 2
