### ISSUE TITLE
A small typo in README.md

### ISSUE THREAD

**Issue by gamtiq** [fergaldoyle/vue-form#31]
There is a small typo in `README.md`:

> You can also get a hook into the internals of v-form-ctrl to _mange_ control state.

Also there is a typo in comment on [line 329 of vue-form.js](https://github.com/fergaldoyle/vue-form/blob/master/vue-form.js#L329):

> overall field _vadility_

**Comment by fergaldoyle** [comment]
Closing Vue 1 compatible version issues.
