### ISSUE TITLE
Globally register validators

### ISSUE THREAD

**Issue by alexjoffroy** [fergaldoyle/vue-form#35]
I use vue-form in several projects, and it's great. So first: thanks for the good work !

Often, I need to use custom validators and I think it could be very nice to be able to register them globally.

So I started to work on a PR. My idea is to use it like this:

``` js
// Globally register some validators
Vue.registerFormValidator('slug', function(val) {
    return /^[a-z0-9-]*$/.test(val);
});
Vue.registerFormValidator('between', function(val, range) {
    range = range.split(',');
    return val >= +range[0] && val <= +range[1];
});

// Create your Vue app as usual
var vm = new Vue({ ... });
```

Then, use them in templates

``` html
<input type="text" v-form-ctrl slug />
<input type="number" v-form-ctrl between="3,15" />
```

What do you think ?

**Comment by fergaldoyle** [comment]
Closing Vue 1 compatible version issues. Global custom validators available in version 2
