### ISSUE TITLE
passing other arguments to customValidator

### ISSUE THREAD

**Issue by Chaoimhin** [fergaldoyle/vue-form#37]
I'm currently using the custom-validator feature to return the result of sever side field validations. In this use case it would be ideal to pass the name of the field being validated instead of only the value to the custom-validator function.

So after my ajax promise is resolved I set a boolean for the validated field in a validations object  and then I call the validate method which triggers the custom validator:
```javascript
ajaxValidator: function (value,fieldName) {
            if(typeof this.validations[fieldName] != 'undefined') return this.validations[fieldName];
            return true;
 }
```

Can your code be adapted to accommodate this easily or Is there a better way to approach this?

**Comment by fergaldoyle** [comment]
Closing Vue 1 compatibile version issues.
