### ISSUE TITLE
Vue 2 Support

### ISSUE THREAD

**Issue by cezarpretto** [fergaldoyle/vue-form#38]
@fergaldoyle Is it working for vue 2?

**Comment by gregorskii** [comment]
This is not working for me in vue2.

Any plans to update?

**Comment by Doogiemuc** [comment]
Hello Fergaldoyle!  Can please just give a rough estimation what you think how long an update of vue-form for Vue 2.0 would take in implementation time?   Some hours?  Some days?   A complete rewrite?    What would you estimate?     If it is not too much, I'd volunteer.

**Comment by fergaldoyle** [comment]
I've have a version prototyped for Vue2. I'll kick myself in the ass and get it done hopefully by the weekend.

**Comment by gregorskii** [comment]
👍🙏

**Comment by srax47** [comment]
@fergaldoyle any update on this?

**Comment by fergaldoyle** [comment]
Work in progress in next branch
https://github.com/fergaldoyle/vue-form/tree/next

A few days to polish it and release.

**Comment by fergaldoyle** [comment]
Version 2.0 released
