### ISSUE TITLE
form error show on $submitted

### ISSUE THREAD

**Issue by mcrider** [fergaldoyle/vue-form#39]
Does the `$submitted` boolean for show work? I can't get it to, and have to use CSS to hide the form error until the form gets the f-form-submitted class is set.  Here's what I'm trying to do (in pug markup):

```
form-errors(field="username" show="$invalid && $submitted")
  pre(slot="required") Username required
```

The `$invalid` boolean works properly.

**Comment by fergaldoyle** [comment]
`$submitted` is now supported in `show` in latest release. I decided to change the API a bit, meaning `form-errors` has been replaced by `field-messages`, with the `field` prop replaced by `name`.
