### ISSUE TITLE
Dynamic attributes are not resolved

### ISSUE THREAD

**Issue by azamat-sharapov** [fergaldoyle/vue-form#4]
Plugin does not resolve dynamic attributes, such as: `v-bind:name` or `:name` on `v-form-ctrl` fields (says "Name attribute must be populated").

Not sure it's bug of feature..

**Comment by fergaldoyle** [comment]
Dynamic name attribute is not yet supported. Is your from input inside a v-for or being dynamically created?

**Comment by azamat-sharapov** [comment]
It's inside `v-for`, yes. It's `v-for`ring component, which has input field in it's template. So I wanted to pass `name` and `custom-validator` through props. 

Temporary changing [this line](https://github.com/fergaldoyle/vue-form/blob/master/vue-form.js#L244) into `this.el.getAttribute('name') || this.el.getAttribute(':name')` works as a quick workaround, but when it comes to adding attributes as object `v-bind="{'name': 'blah', ...}"` that hack won't work, involves too much work in that case I'm guessing..

**Comment by ryanscherler** [comment]
Any thoughts on how to do validation in a v-for as described above? I too have an issue with dynamic component inputs and not sure how I can validate them.

**Comment by fergaldoyle** [comment]
I've added support for validation inside a v-for and also inside a component.

You can also now use `v-bind="{'name': 'blah', ...}"` syntax for setting name and validation attributes.

**Comment by ryanscherler** [comment]
So awesome! Thanks!

**Comment by azamat-sharapov** [comment]
Thanks!
