### ISSUE TITLE
CSS Example

### ISSUE THREAD

**Issue by LuckyURE** [fergaldoyle/vue-form#40]
Sorry, but I'm having trouble understanding how the CSS classes are being changed on the form and no example exists.

Here is what I tried to add my custom CSS to change the color of the error text:

`<validate tag="label">
    <span class="form-title">Cell Phone</span>
    <input class="form-control" 
                type="tel" 
                v-model="cell_phone"
                name="cell_phone" 
                pattern="^\d{10}$"/>
    <form-errors field="cell_phone"show="$dirty && $touched">
        <div :class="{ 'error': vf-form-invalid }"
                slot="pattern">Phone number must be 10 numbers</div>
    </form-errors>
</validate>`

**Comment by LuckyURE** [comment]
Update, I got it to work by checking: this.formstate.$invalid  but I'm not sure if that's the proper way or not for the library.

**Comment by fergaldoyle** [comment]
Classes are automatically added to and removed from the vue-form element, validate element and v-model element.

See the various classes here
https://github.com/fergaldoyle/vue-form#state-classes

You could do something like this:

```html
<validate tag="label">
   <span class="form-title">Cell Phone</span> 
   <input class="form-control" type="tel" v-model="cell_phone" name="cell_phone" pattern="^\d{10}$"/> 
   <form-errors field="cell_phone"show="$dirty && $touched" class="form-message">
      <div slot="pattern">Phone number must be 10 numbers</div>
   </form-errors>
</validate>
```
```css
.vf-container-invalid .form-message {
   color: red
}
```

**Comment by LuckyURE** [comment]
That worked perfectly!  Thanks!
