### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by romandragan** [fergaldoyle/vue-form#43]
When using the plugin in SSR application there is `window is not defined` issue at [`dist/vue-form.js:46`](https://github.com/fergaldoyle/vue-form/blob/master/dist/vue-form.js#L46).

What about fixing it with changing this:
```js
Promise: window.Promise
```
to:
```js
Promise: (typeof window !== 'undefined' ? window.Promise : undefined)
```

Then, Server-Side Rendering would be work fine.

P.S. @fergaldoyle, if you prefer, I could submit PL for that.

**Comment by fergaldoyle** [comment]
Please do make a PL, I'm not set up for SSR so would be good if you can verify if it works. Setting Promise undefined, will this then cause issues for async validators?

**Comment by jvbianchi** [comment]
Instead of using undefined, for node maybe you can use:
```
global.Promise
```

**Comment by fergaldoyle** [comment]
Environment global detected with ba774845d924eb2cecf0202e8aea16da312ac0dd

**Comment by romandragan** [comment]
Now it's working fine
