### ISSUE TITLE
$invalid/$valid should only be evaluated when $dirty

### ISSUE THREAD

**Issue by airtonix** [fergaldoyle/vue-form#5]
Basically do not determine if the for or any of the fields are invalid until the form is dirty.

**Comment by fergaldoyle** [comment]
Only `required` fields are immediately validated and set $valid/$invalid to prevent submission of data without required fields. This behavior matches Angular forms.

**Comment by DrCord** [comment]
required fields should not be validated until input has happened... this causes all sorts of issues with the message displaying immediately on page load, really bad UI.
