### ISSUE TITLE
Reset form to be untouched/pristine

### ISSUE THREAD

**Issue by dan-zheng** [fergaldoyle/vue-form#55]
I'm using a form on a page (in a modal). After the form is submitted, there is no redirect and the fields of the form are set blank. However, when the form (in the modal) is opened again, the fields are marked as being touched and not pristine. This is not ideal because my CSS styling shows the fields as immediately being red, even though the form is being opened for the first time after submission.

I'm wondering if it's possible add a "reset form" function that resets the fields of the form to be untouched and pristine again. I could then call this function after the form is submitted and the fields have been reset.

I will try to add a minimal example that demonstrates this phenomenon soon.

**Comment by fergaldoyle** [comment]
That's something that could be added. In the meantime you could have the form inside a v-if so that gets destroyed when inactive and re-initalized with fresh state when active.

**Comment by kaleb** [comment]
@dan-zheng,

Could also do something like this for now:

    Object.keys(myFormState).forEach(k => {
      if (k[0] == '$') return;
      const field = myFormState[k];
      field._setPristine();
      field._setUntouched();
    });

**Comment by dan-zheng** [comment]
@fergaldoyle @kaleb Thank you for the suggestions! I'll try to add this feature and submit a pull request within the week, if no one else attempts it.

**Comment by fergaldoyle** [comment]
Added reset in latest release
https://github.com/fergaldoyle/vue-form/releases/tag/4.0.2
