### ISSUE TITLE
Problem with vue.js 2.3.0

### ISSUE THREAD

**Issue by exgphe** [fergaldoyle/vue-form#56]
After upgrading to vue.js 2.3.0, the usage:
```
import VueForm from 'vue-form'
// ...
mixin: [VueForm]
```

will cause a strange bug. Instead, we have to use:

`mixin: [new VueForm()]`

**Comment by fergaldoyle** [comment]
Looks like a change in Vue mixin api, not sure if it's intentional or not. Opened an issue here: https://github.com/vuejs/vue/issues/5567

**Comment by fergaldoyle** [comment]
Workaround added to latest release
https://github.com/fergaldoyle/vue-form/releases/tag/4.0.2
