### ISSUE TITLE
Presence of duplicated symmetric flags is confusing

### ISSUE THREAD

**Issue by stefanoborini** [fergaldoyle/vue-form#57]
Duplicated symmetric flags such as $dirty/$pristine or $valid/$invalid are terribly confusing, especially when one wants to change the state of the formstate from the outside (e.g. for cross validation)

**Comment by fergaldoyle** [comment]
It's not THAT confusing.  In what way are you trying to modify these flags? 
Your model should be thing that controls these flags / state. You could use conditional validators or custom validators to control form state from the outside.

**Comment by stefanoborini** [comment]
It is. One assumes they are symmetric, but don't behave as such. In practice, I don't see a valid reason to have two flags that are always supposed to be a NOT of the other. You can't have something both valid and invalid.

**Comment by fergaldoyle** [comment]
Why are you setting flags manually? If your model is invalid based on the validators applied to that model, it is invalid.  Manually changing `$valid` to true is while your model is invalid is more confusing than having `$valid` and `$invalid` flags.

Anyway it's a design choice to have that flags as they are and it won't be changing.

**Comment by stefanoborini** [comment]
I am changing them manually because I have to perform cross validation of some fields.
