### ISSUE TITLE
$dirty remains true after changes are undone

### ISSUE THREAD

**Issue by jacksonp** [fergaldoyle/vue-form#58]
Using vue-form, if I make a text change in an input, its $dirty property changes from false to true - as expected.

If I then undo that change, reverting the input's value back to the original value, the $dirty property remains true - which is not ideal in my use case.

I've previously used https://github.com/codedance/jquery.AreYouSure - which would mark the form as being clean if changes are made and then undone. Is it possible to get vue-form working the same way?

**Comment by fergaldoyle** [comment]
Once a user interacts with a form field it becomes dirty. You can reset form state with the reset method.

**Comment by jacksonp** [comment]
Ok, I'm just saying it would be nice if a user undoes their changes for the field (and maybe form) to return to a clean state automatically - is there any reason that behaviour isn't desirable?
E.g. in my case, I don't want the submit button to be active unless there are actual changes from the original values in the form, and I'd assumed I could use $dirty to determine this.

**Comment by fergaldoyle** [comment]
No particular reason it's not desirable, it's just how it works with this component. Logic behind when something is dirty or touched mirrors Angular form validation. If a user touches and changes a field, it becomes dirty, and stays dirty even if they press backspace to revert to the original value.

In your case you could clone a master copy of the initial form data, and only enable the submit button if the current form data is different to the master copy.  Comparing the JSON stringified version of both objects is usually good enough.
