### ISSUE TITLE
slot="maxlength" doesn't show error

### ISSUE THREAD

**Issue by krasevych** [fergaldoyle/vue-form#60]
I tested the example https://jsfiddle.net/fergal_doyle/zfqt4yhq/
and when I wrote more than 50 symbols in field `name="comments"`, it doesn't show corresponding error message

**Comment by fergaldoyle** [comment]
What browser? I found most browsers don't allow you enter more than the number of chars in defined by `maxlength` so the error will never show.

**Comment by krasevych** [comment]
I use Chrome Version 57.0.2987.133

**Comment by Narretz** [comment]
@fergaldoyle is right, browsers (at least FF and Chrome) restrict the possible input to the maxlength. It's quite easy to see, you cannot enter more than 50 characters. When you paste something, it also gets cut off at the maxlength.

**Comment by krasevych** [comment]
if I want to show error message, should I use pattern instead?

**Comment by fergaldoyle** [comment]
You can't enter more than 50 characters on chrome, therefore the field will never be invalid for max length.
