### ISSUE TITLE
IE problem

### ISSUE THREAD

**Issue by tiagofscoelho** [fergaldoyle/vue-form#64]
Hello,
I am using vue-form and I am having problems with IE. It's working as expected on Chrome, Safari and Firefox. 

![screen shot 2017-05-22 at 09 57 44](https://cloud.githubusercontent.com/assets/7908689/26300255/824a1508-3ed5-11e7-94eb-f48f96a6b033.png)

I already have the `<!DOCTYPE html>` and `<meta http-equiv="X-UA-Compatible" content="IE=edge">` on my HTML file, I tried to add a querySelectorAll Polyfill but the problem wasn't fixed.

Do you have any suggestions?

**Comment by fergaldoyle** [comment]
What version of Vue, vue-form and IE?

Does this work for you?
https://github.com/fergaldoyle/vue-form/blob/master/example/bootstrap.html

**Comment by tiagofscoelho** [comment]
@fergaldoyle I updated Vue to 2.3.3 and vue-form to 4.1.1 and the problem was fixed. Thanks. 👍 

Just for reference, I was using Vue 2.2.4 and vue-form 4.0.1 on IE11.
