### ISSUE TITLE
issue with vue-router's "beforeRouteEnter" ?

### ISSUE THREAD

**Issue by tech-no-logical** [fergaldoyle/vue-form#65]
hi, 

I use the mentioned hook to fetch data to dynamically render a form using vue-form. however, doing this generates ugly errors like 

vue.esm.js?65d7:434 [Vue warn]: Error in render function: "TypeError: Cannot read property 'length' of undefined"

when rendering an array of checkboxes defined by the loaded data. the errors are exactly the same as if I used the 'created' hook instead of 'beforeRouteEnter', but the latter should wait for data to be loaded (console sort of confirms that it does).

code is here : 
http://plnkr.co/edit/iUZXWFl3UPT6gSp54mUh?p=preview

but keep in mind that here I have the 'created' hook in use, whilst in my code that's the 'beforeRouteEnter'. the errors are the same though.

**Comment by tech-no-logical** [comment]
to add : inhibiting rendering by enclosing everything with <div v-if="loaded">...</div> fixes it, but this solution should be equivalent to using beforeRouteEnter (afaik)

**Comment by fergaldoyle** [comment]
Looks like Vue 2.3.x has changed a bit. `$slots.default` used to instantly be defined, now it seem the render function is called with it undefined first.

Latest release handles this
https://github.com/fergaldoyle/vue-form/releases/tag/4.1.1
