### ISSUE TITLE
Element with v-model not found

### ISSUE THREAD

**Issue by jofftiquez** [fergaldoyle/vue-form#66]
This warning `Element with v-model not found` prints on the console when I try to watch `formstate`. 

`v-model` is present on both email and password field.

```
watch: {
    formState (f) {
     // prints upon loading of component
     // but not whenever I type on the fields
      console.log('dirty', f.email)
      console.log('error', f.password)
    }
  },
```

**Comment by fergaldoyle** [comment]
Does it warn but everything still works? Sometimes it can give a false positive. I'll remove it in next release

**Comment by jofftiquez** [comment]
Yes everything works, but not during `watch` event. I'm using `vuetifyjs` by the way, do you think there's a conflict with `props`?

**Comment by fergaldoyle** [comment]
Deep watch seems to work fine:
https://jsfiddle.net/g2enqy08/3/

**Comment by jofftiquez** [comment]
@fergaldoyle It did. Thanks.
