### ISSUE TITLE
It's would be great to support debounce validate

### ISSUE THREAD

**Issue by dsonet** [fergaldoyle/vue-form#67]
Can set a configurable delay for validate method, like 500ms?

**Comment by kaleb** [comment]
I have validation working on input no problem. Can you make a minified test
case and share?

**Comment by dsonet** [comment]
@kaleb Yes, you're right. It works fine with input event. What I want  is can have a delay with it while typing.

**Comment by fergaldoyle** [comment]
With v4.2.0 you can now debounce, e.g.

`<validate :debounce="500">`

**Comment by dsonet** [comment]
@fergaldoyle Thanks. That's great.
