### ISSUE TITLE
Is there a convenient way to focus the invalid input element?

### ISSUE THREAD

**Issue by dsonet** [fergaldoyle/vue-form#68]
Sometimes when there are invalid fields, we want to focus the first input element.(only when triggered by other buttons, not the element's self blur event)

**Comment by fergaldoyle** [comment]
A common pattern is to display form error messages in a list above the form on submit, each message is a `label` with `for` attribute pointing to the invalid input id. Using `auto-label` helps for this, e.g.  https://jsfiddle.net/fergal_doyle/bqys2p5y/

**Comment by dsonet** [comment]
OK, thanks.
