### ISSUE TITLE
error occured when using vuejs in production

### ISSUE THREAD

**Issue by ablipan** [fergaldoyle/vue-form#7]
![image](https://cloud.githubusercontent.com/assets/4636330/11432880/806b421e-94f1-11e5-90d9-0ed24185150e.png)

maybe the reason is
//  vue/dist/vue.js
```javascript
 7569      // store directives on node in dev mode
 7570      if ('development' !== 'production' && this.el) {
 7571:       this.el._vue_directives = this.el._vue_directives || [];
 7572:       this.el._vue_directives.push(this);
 7573      }
 7574    }
```

**Comment by fergaldoyle** [comment]
Fixed for now, although we can't use v-bind object syntax to set multiple validation attributes in production for now.
