### ISSUE TITLE
Reset form

### ISSUE THREAD

**Issue by EnfyS2** [fergaldoyle/vue-form#70]
I have a dialog with a form and when i close it, it is supposed to clear all fields and return to the original form, but they stay red. I use _reset() to reset the form. How can i resolve it?

**Comment by fergaldoyle** [comment]
Should work, example?On 27 Jun 2017 3:19 pm, EnfyS2 <notifications@github.com> wrote:I have a dialog with a form and when i close it, it is supposed to clear all fields and return to the original form, but they stay red. I use _reset() to reset the form. How can i resolve it?

**Comment by EnfyS2** [comment]
When i click the close button i call this method, to reset the model for each input and then reset to the formstate

resetForm: function () {
        for( var item in this.form ) {
          if( Array.isArray( this.form[item] ) ){
            this.form[item] = []
          } else if( typeof this.form[item] === 'string' ){
            this.form[item] = ""
          } else {
            this.form[item] = {}
          }
        }
        this.formstate._reset();
},

**Comment by EnfyS2** [comment]
And this is my form

<v-dialog v-model="formDialog" persistent width="800" height="400">
              <v-card>
                <v-card-row>
                  <v-card-title>{{title}}</v-card-title>
                  <v-btn icon class="blue--text" @click.native="formDialog = false; resetForm()"><v-icon>close</v-icon></v-btn>
                </v-card-row>
                <v-card-row>
                  <v-card-text>
                    <vue-form :state="formstate" @submit.prevent="onSubmit" id="formDialog">

                      <validate tag="label">
                        
                        <v-menu lazy :close-on-content-click="true" v-model="requestDate" transition="v-scale-transition" offset-y :nudge-left="40" name="requestDate">
                          <v-text-field slot="activator" label="Data do pedido" @input="convertToJson" v-model="form.requestDate" prepend-icon="event" required readonly></v-text-field>
                          <v-date-picker v-model="form.requestDate" no-title></v-date-picker>
                        </v-menu>
                        
                      </validate>             

                      <validate tag="label">
                        
                        <v-menu lazy :close-on-content-click="true" v-model="installationDate" transition="v-scale-transition" offset-y :nudge-left="40" name="installationDate">
                          <v-text-field slot="activator" label="Data de instalação" v-model="form.installationDate" prepend-icon="event" required readonly></v-text-field>
                          <v-date-picker v-model="form.installationDate" no-title></v-date-picker>
                        </v-menu>
                        
                      </validate>

                      <validate tag="label">
                        
                        <v-select v-bind:items="selects.collaborator" v-model="form.collaborator" label="Colaborador" dark max-height="160" name="collaborator" required></v-select>
                        
                      </validate>

                      <validate tag="label">
                        
                        <v-select v-bind:items="selects.client" v-model="form.client" label="Cliente" dark max-height="160" name="client" required></v-select>
                        
                      </validate>     

                      <validate tag="label">
                        
                        <v-select label="Produtos" v-bind:items="selects.product" v-model="form.product" multiple max-height="160" name="product" required></v-select>
                        
                      </validate>          

                      <validate tag="label">
                        
                        <v-select label="Versão do(s) Produto(s)" v-bind:items="selects.version" v-model="form.version" dark max-height="160" name="version" required></v-select>
                        
                      </validate>

                      <validate tag="label">
                        
                        <v-select label="Ambiente" v-bind:items="selects.environment" v-model="form.environment" dark max-height="160" name="environment" required></v-select>
                        
                      </validate>

                      <validate tag="label">
                        
                        <v-select label="Release Banka" v-bind:items="selects.releaseBanka" v-model="form.releaseBanka" dark max-height="160" name="relBanka" required></v-select>
                        
                      </validate>

                      <validate tag="label">
                        
                        <v-text-field v-model="form.notes" label="Notas" name="notes" multi-line required></v-text-field>
                        
                      </validate>

                      
                      <v-btn class="blue--text darken-1" flat type="submit">{{type}}</v-btn>
                      
                    </vue-form>

**Comment by EnfyS2** [comment]
And this is my form 
`<v-dialog v-model="formDialog" persistent width="800" height="400">
              <v-card>
                <v-card-row>
                  <v-card-title>{{title}}</v-card-title>
                  <v-btn icon class="blue--text" @click.native="formDialog = false; resetForm()"><v-icon>close</v-icon></v-btn>
                </v-card-row>
                <v-card-row>
                  <v-card-text>
                    <vue-form :state="formstate" @submit.prevent="onSubmit" id="formDialog">

                      <validate tag="label">
                        
                        <v-menu lazy :close-on-content-click="true" v-model="requestDate" transition="v-scale-transition" offset-y :nudge-left="40" name="requestDate">
                          <v-text-field slot="activator" label="Data do pedido" @input="convertToJson" v-model="form.requestDate" prepend-icon="event" required readonly></v-text-field>
                          <v-date-picker v-model="form.requestDate" no-title></v-date-picker>
                        </v-menu>
                        
                      </validate>             

                      <validate tag="label">
                        
                        <v-menu lazy :close-on-content-click="true" v-model="installationDate" transition="v-scale-transition" offset-y :nudge-left="40" name="installationDate">
                          <v-text-field slot="activator" label="Data de instalação" v-model="form.installationDate" prepend-icon="event" required readonly></v-text-field>
                          <v-date-picker v-model="form.installationDate" no-title></v-date-picker>
                        </v-menu>
                        
                      </validate>

                      <validate tag="label">
                        
                        <v-select v-bind:items="selects.collaborator" v-model="form.collaborator" label="Colaborador" dark max-height="160" name="collaborator" required></v-select>
                        
                      </validate>

                      <validate tag="label">
                        
                        <v-select v-bind:items="selects.client" v-model="form.client" label="Cliente" dark max-height="160" name="client" required></v-select>
                        
                      </validate>     

                      <validate tag="label">
                        
                        <v-select label="Produtos" v-bind:items="selects.product" v-model="form.product" multiple max-height="160" name="product" required></v-select>
                        
                      </validate>          

                      <validate tag="label">
                        
                        <v-select label="Versão do(s) Produto(s)" v-bind:items="selects.version" v-model="form.version" dark max-height="160" name="version" required></v-select>
                        
                      </validate>

                      <validate tag="label">
                        
                        <v-select label="Ambiente" v-bind:items="selects.environment" v-model="form.environment" dark max-height="160" name="environment" required></v-select>
                        
                      </validate>

                      <validate tag="label">
                        
                        <v-select label="Release Banka" v-bind:items="selects.releaseBanka" v-model="form.releaseBanka" dark max-height="160" name="relBanka" required></v-select>
                        
                      </validate>

                      <validate tag="label">
                        
                        <v-text-field v-model="form.notes" label="Notas" name="notes" multi-line required></v-text-field>
                        
                      </validate>

                      
                      <v-btn class="blue--text darken-1" flat type="submit">{{type}}</v-btn>
                      
                    </vue-form>`

**Comment by EnfyS2** [comment]
This is my form sorry to send it by a txt file 
[form.txt](https://github.com/fergaldoyle/vue-form/files/1105826/form.txt)

**Comment by fergaldoyle** [comment]
Can you create a basic example in jsfiddle? e.g. fork this https://jsfiddle.net/fergal_doyle/fz8j0ud3/

Note i had to put `reset()` inside a `$nextTick` for it to mark fields pristine. Will look into it. Not sure if it's related to your issue.

**Comment by EnfyS2** [comment]
This example https://jsfiddle.net/EnfyS/ogz0pvzv/ shows exactly my problem. If you write inside the input and then close or click in button 'insert', the input stays red.

**Comment by fergaldoyle** [comment]
The styling comes from vuetiy, with class `input-group--error`.

One way to get around it is to have the contents of the modal re-render when the modal is open, e.g.
`<vue-form v-if="formDialog" :state="formstate" @submit.prevent="onSubmit">`

**Comment by EnfyS2** [comment]
Thanks for the help :smiley:
