### ISSUE TITLE
submit the form programatically?

### ISSUE THREAD

**Issue by JsonHunt** [fergaldoyle/vue-form#71]
I've tried to use this.$refs.myForm.$el.submit(), but it doesn't seem to work: $submitted is still false and @submit is not triggered

**Comment by fergaldoyle** [comment]
`$el.submit()` doesn't trigger the `submit` event which `vue-form` listens for.

I've added a `_submit` method which you can manually call, see:
https://github.com/fergaldoyle/vue-form/releases/tag/4.3.2

**Comment by chrisnicola** [comment]
@fergaldoyle so this doesn't seem to submit the form programmatically, it just sets $submitted = true. Is there a reason `$el.submit()` doesn't work? It seems like it should.

Why not just have formstate.submit() tigger the normal submitted event?
