### ISSUE TITLE
customValidator - "TypeError: _this3._validators[validator] is not a function"

### ISSUE THREAD

**Issue by TheGinJiCode** [fergaldoyle/vue-form#72]
Hi,
I'm trying to create a customeValidator.
I have 3 fields: firstName, middleName, and lastName.
all of them are NOT required, BUT if the use inputs onto one of them then automatically all of them
will be required.

so i tried this.
:custom="{userValidator: customValidator(user)}"

customValidator (value) {
 console.log(value)
 return value === 'custom'
}

It actually works, it return the user. BUT there is that error or warning "TypeError: _this3._validators[validator] is not a function". 

Is there an alternative way? so that there will be no errors/warning shown.

Thanks :)

**Comment by fergaldoyle** [comment]
Can you replicate the error in jsfiddle?

You could also use conditional required fields with the `:required` binding

**Comment by TheGinJiCode** [comment]
Hi,

Thanks for the reply.
I figure out using :required as stated in your doc. 
And I see you also suggested it. Thanks.
Sorry I can't replicate it in jsfiddle. But the error only happens when I use this in custom.
:custom="{customValidator: customValidator(data)}"
