### ISSUE TITLE
Using :value="false" with required fails validation

### ISSUE THREAD

**Issue by at0g** [fergaldoyle/vue-form#73]
As per issue #27
It appears the original issue was closed by the creator, but was never resolved.

**Comment by kaleb** [comment]
This is as designed. If a Boolean value is used and it is required, the
true state would be the fulfillment of the retirement.

**Comment by at0g** [comment]
My use case is that I have 2 radio buttons, one `true` and one `false`, with neither value initially selected. I would like to validate that the user has chosen an option, rather than `undefined`.

**Comment by fergaldoyle** [comment]
Changing the current implementation to handle user entered `false` values is likely to be a breaking change, so I've added a `bool` option to tell the required validator that `false` is passable value, e.g.

```
<validate>
  <label>Yes <input type="radio" :value="true" v-model="test" name="radio" required /></label>
  <label>No <input type="radio" :value="false" v-model="test" name="radio" required bool /></label>
</validate>
```

https://github.com/fergaldoyle/vue-form/releases/tag/4.3.3

**Comment by chrisnicola** [comment]
Just ran into this. It is undocumented and doesn't seem ideal as a design. Is this something that can be changed in the next major version.

I mean I realize this is a breaking change, but I can't see how or why someone would want the value "false" the be the same as being absent.
