### ISSUE TITLE
Does it works with checkboxes?

### ISSUE THREAD

**Issue by alexey-sh** [fergaldoyle/vue-form#75]
I even didn't see any example

**Comment by fergaldoyle** [comment]
Works the same as other field. Mostly you'll use the `required` validator.

Updated example to include a checkbox: https://jsfiddle.net/fergal_doyle/zfqt4yhq/

**Comment by alexey-sh** [comment]
I've modified the example https://jsfiddle.net/w74744hz/2/
no there are two checkboxes with the same name. first checkbox is checked by default. the second is unchecked.
I noticed a bit weird behaviour:
1. click "no"
2. click "yes"
3. the error appears (no checked, yes unchecked)
4. click no
5. click no
6. the error disappeared (no checked, yes unchecked).

What I'm doing wrong?

**Comment by fergaldoyle** [comment]
Multiple checkboxes inside a single `<validate />` tag will probably only work if v-model is an array which each of the checkboxes is bound to, e.g.

```
          <validate>
            <input type="checkbox" value="Jack" v-model="model.multicheck" required name="multicheck"/>
            <input type="checkbox" value="John" v-model="model.multicheck" required name="multicheck"/>
            <input type="checkbox" value="Mike" v-model="model.multicheck" required name="multicheck"/>
          </validate>
```

**Comment by alexey-sh** [comment]
https://jsfiddle.net/w74744hz/3/
I've added
```
created: function () {
  var that = this;
  	setTimeout(function () {
    that.multicheck.push('1')
    }, 1000);
  }
```
and now the model contains the value, checkbox is checked but formstate still contains the "required" error.

**Comment by fergaldoyle** [comment]
What exactly is it you are trying to achieve?

**Comment by alexey-sh** [comment]
@fergaldoyle validate checkboxes

**Comment by fergaldoyle** [comment]
Well the only why checkboxes work are like the example I provided above.
