### ISSUE TITLE
Manually triggering validation

### ISSUE THREAD

**Issue by diachedelic** [fergaldoyle/vue-form#76]
I am making a user registration form, and trying to output a nice error for when the email is already taken - however, I only find that out once I try to submit the form to the server and fail.  I can't figure out how to force revalidation.

```
{
  data: {
    email: 'exists@blah.com',
    existingEmail: null,
  },
  methods: {
    submit() {
      // try to submit to server, and email exists
      this.existingEmail = this.email

      // TRIGGER REVALIDATION
    },
    emailExists(value) {
      return value !== this.existingEmail
    },
  }
}
```
```
        <validate :custom="{ exists: emailExists }">
          <field-messages class="vf-messages" name="email">
            <div slot="required">Please enter your email</div>
            <div slot="email">That email address is not valid</div>
            <div slot="exists">
              That email already exists - go to 
              <router-link :to="{ name: 'login' }">login</router-link>
            </div>
          </field-messages>

          <input name="email" v-model="email" type="email" placeholder="Email"
            required ref="email" />
        </validate>
```

Any ideas?

**Comment by fergaldoyle** [comment]
An async validator would work here if you have an endpoint you can hit to determine if the email is taken before you submit.

**Comment by diachedelic** [comment]
That did occur to me - but how about the general case where a submission is rejected by the server, and you'd like to show some error for a specific field?  I.e. incorrect password?

It would be really cool to be able to set an error like

```
this.formstate.email.$error.custom = true

<field-messages>
  ...

  <div slot="custom">
    Server did not like this value
  </div>
</field-messages>
```

And have it's message appear.  What are your thoughts?

**Comment by fergaldoyle** [comment]
Using the current API, a Global custom validator would also work.  You could maintain flags for `isEmailTaken` or `isPasswordInvalid` and set them to `false` on server response. Because a custom validator watches bound values, when `isEmailTaken` is set to true,  the field will display the error and receive invalid state.

```javascript
var options = {
  validators: {
    'is-taken': function(value, attrValue, vnode) {
      return !attrValue;
    }
  }
}

// Vue.use(VueForm, options);
// or
// mixins: [new VueForm(options)]
```

```html
<validate>
  <field-messages name="email">
    <div slot="is-taken">This email address is already taken</div>
  </field-messages>
  <input :is-taken="isEmailTaken" name="email" v-model="email" type="email" />
</validate>
```

```javascript
{
  //...

  data: {
    isEmailTaken: false
  }

  //...

  methods: {
    submit() {
      submitToServer().then(()=>{
        // server responds that the email is taken
        this.isEmailTaken = true;
      });
    }
  }

  //...
}
```

Another option might be to allow `<validate>` accept a prop called `watch` which could watch key value pairs, e.g. `<validate :watch={'is-taken': isEmailTaken } />`.   `isEmailTaken` could be a data property or a computed property which would be handy.

**Comment by diachedelic** [comment]
That first solution is fine for my purposes, thanks very much.  I think I prefer using a global validator than using a component method, it's a cleaner separation (I prefer to mixin VueForm rather than `.use()` it globally anyway).

What if you could use a watched data/computed prop as a custom validator, not just a method?

```javascript
{
  //...

  data: {
    isEmailAvailable: true
  }

  //...

  methods: {
    submit() {
      submitToServer().then(()=>{
        // server responds that the email is taken
        this.isEmailAvailable = false;
      });
    }
  }

  //...
}
```
```html
<validator :custom="{ 'is-taken': isEmailAvailable }">
  <field-messages name="email">
    <div slot="is-taken">This email address is already taken</div>
  </field-messages>
  <input name="email" v-model="email" type="email" />
</valdator>

**Comment by jezmck** [comment]
Is there a simple, single line, way to manually trigger validation?

**Comment by fergaldoyle** [comment]
You can now use a data / computed property and a way to manually trigger validation has been added:
https://github.com/fergaldoyle/vue-form/releases/tag/4.5.0

**Comment by diachedelic** [comment]
Yes!  This is great, my component now looks like the following:

```
{
  //...

  data: {
    isEmailAvailable: true
  }

  //...

  methods: {
    resetErrors() {
      this.isEmailAvailable = true
    }
    submit() {
      this.resetErrors()

      submitToServer().then(()=>{
        // server responds that the email is taken
        this.isEmailAvailable = false;
      });
    }
  }

  //...
}
```
```
<!-- reset the validation errors once the user starts changing the form data -->
<fieldset @input.capture="resetErrors">
        <validate :custom="{ 'exists': isEmailAvailable}">
          <field-messages>
            ...
            <div slot="exists">Email address is not registered.</div>
          </field-messages>

          <input v-model="email" />
        </validate>
</fieldset>
```

Thanks so much!

**Comment by diachedelic** [comment]
Would to be possible for `.validate()` to return a promise which would indicate when it's done?  I am using `await this.$nextTick()` for now, which is not quite as nice.
