### ISSUE TITLE
Please add documentation for field-messages w/ custom validators

### ISSUE THREAD

**Issue by matthew-dean** [fergaldoyle/vue-form#77]
I'm finding it hard to add an error message when a custom validator returns false. The documentation is unclear as to what the slot name should be, since it's not a standard one like "required" or "email". If I don't add a slot name, it shows the error message regardless.

**Comment by matthew-dean** [comment]
Found it by trial / error! Can you add the reference to `slot="customValidator"` to the documentation:
`<div slot="customValidator">At least one type must be checked.</div>`

**Comment by fergaldoyle** [comment]
Updated with 6a777dc1dacd9fcd51cfc5ac4d928e80eb975b07
