### ISSUE TITLE
Feature request: global validation "show" behavior

### ISSUE THREAD

**Issue by matthew-dean** [fergaldoyle/vue-form#78]
I found myself doing a lot of this: 
```html
<field-messages name="last_name" show="$touched || $submitted">
  <div slot="required">This field is required.</div>
</field-messages>
```
It would be nice to make the validation "show" rules global (to the form/component). I can't think of a scenario where I'd want the form to behave differently (as far as showing error messages) per field, so this design is a bit perplexing in the first place.

**Comment by fergaldoyle** [comment]
You can now set the default value of `show` through with the `showMessages` option or the `show-messages` prop on `vue-form`, e.g. 

```
<vue-form show-messages="$touched || $submitted" ... />
```
