### ISSUE TITLE
How do I mark a form as pristine?

### ISSUE THREAD

**Issue by seyhbold** [fergaldoyle/vue-form#8]
Hi,

I have a vue-form component with a model passed as prop.
When the model is resolved asynchronously (in the parent component) the form is set dirty.

Is there any way to prevent this?

Thanks a lot
Ludwig

**Comment by fergaldoyle** [comment]
Can you provide an example in JSFiddle? 

Here's a base fiddle: http://jsfiddle.net/4bcchvg5/

**Comment by seyhbold** [comment]
Hmm, I don't know how to recreate an example in JSFiddle.
I am using `vue-loader`, `vue-resource` and `vue-router`.

I created the Form like:
```html
<template>
    <form v-form name="myform">
        <input type="text" v-model="model.title" v-form-ctrl name="title">
    </form>
</template>

<script type="text/ecmascript-6">
export default {
    name: 'FormComponent',
    props: {
        model: {
            type: Object,
            required: true
    },

}
</script>
```

**Comment by fergaldoyle** [comment]
You can get a hook into the form object using the `hook` attribute.

```javascript
<template>
    <form v-form name="myform" hook="formHook">
        <input type="text" v-model="model.title" v-form-ctrl name="title">
    </form>
</template>

<script type="text/ecmascript-6">
export default {
    name: 'FormComponent',
    props: {
        model: {
            type: Object,
            required: true
    },
    data() {
        return {
            myformform: {}
        }
    },
    methods: {
        formHook: function (form) {
           // form.setPristine(); // this is how to setPristine
       }
    }
}
</script>
```

Because your form is in a component, you'll have to pass up the form object to the parent. You could do this with an event or synced prop. Once you set the model in the parent, you'll then have to use `nextTick` and `setPristine`

```
.then((response) => {
	this.$nextTick(() => {
		this.form.setPristine();
	});
	return { model: response.data }
})
```

I may re-think how and when the form / form controls get set dirty in the next major release.

**Comment by seyhbold** [comment]
Hmm, still no luck.

I've got the hook and my `.then` method looks like this:

```javascript
.then(function (data) {
    self.$nextTick(function () {
        self.$refs.formComponent.form.setPristine()
        log.debug('setPristine invoked')
    })
    log.debug('data ready')
    return { model: data}
})
```

The log output is as expected:
```
data ready
setPristine invoked
```

But the form is still dirty.
I debugged through `vue-form.js` and found that the `$watch` that is created for each `formCtrl` is triggered twice. i.e.
1st time title value: *undefined* oldValue: *undefined*
2nd time title value: *'FRANZ LISZT'* oldValue: *undefined*

Do you have a hint how I can hunt down the source of this trigger?


Thanks you very much
Ludwig

**Comment by fergaldoyle** [comment]
Closing Vue 1 compatible version issues.
