### ISSUE TITLE
How can I make it work with input[type=file]?

### ISSUE THREAD

**Issue by leadream** [fergaldoyle/vue-form#80]
At first, thanks for your great plugin!
I'm using vue-form in my website, but it doesn't work for input[type=file]. When I looked into the code, I noticed that the validator binds input element when it has v-model directive, but we can't use this directive on input[type=file]. How can I do to make it work, or vue-form doesn't support input[type=file]? Thanks.

**Comment by fergaldoyle** [comment]
Correct, it needs v-model to exist for it to validate a value. 

You can wrap an `input[type=file]` in a component and handle the file reading and emit the file object to v-model, see simple example (doesn't handle multiple files):
https://jsfiddle.net/fergal_doyle/L1socc1p/

**Comment by leadream** [comment]
Yeah, I'm trying this way. Thanks for your example. It really help.
