### ISSUE TITLE
Doesn't work when autocompleted

### ISSUE THREAD

**Issue by alexey-sh** [fergaldoyle/vue-form#81]
chrome browser sets values but vue-form don't see it. it seems like the library doesn't work when value is updated not from user interaction.

**Comment by fergaldoyle** [comment]
Does Vue itself work with autocomplete? Is the v-model value updated?

**Comment by kaleb** [comment]
https://github.com/vuejs/vue/issues/5248

**Comment by alexey-sh** [comment]
>Does Vue itself work with autocomplete? Is the v-model value updated?
I have no idea. Just decided not use vue. No vue, no problem.

**Comment by fergaldoyle** [comment]
Ok then
