### ISSUE TITLE
[Feature Request] Friendlier error message with missing :state prop

### ISSUE THREAD

**Issue by matthew-dean** [fergaldoyle/vue-form#82]
If you leave off `:state="formstate"` from `<vue-form />`, then you'll get the confusing error
`[Vue warn]: Error in created hook: "TypeError: Cannot convert undefined or null to object"` without a pointer to any line number.

Obviously, this was my mistake, but a friendlier error check for required properties might help someone else in the future.

**Comment by fergaldoyle** [comment]
State now a required prop so Vue will warn if it is missing
https://github.com/fergaldoyle/vue-form/releases/tag/4.4.2
