### ISSUE TITLE
Associated model properties must be defined, no error thrown

### ISSUE THREAD

**Issue by jezmck** [fergaldoyle/vue-form#83]
```js
data() {
      return {
        formstate: {},
        model: {}, // <-- this will cause problems with no console errors
        ...
```

**Comment by fergaldoyle** [comment]
If you don't define the property passed to `v-model` Vue will definitely throw an error.

**Comment by jezmck** [comment]
No, it didn't throw an error.

**Comment by fergaldoyle** [comment]
Example?

**Comment by jezmck** [comment]
https://jsfiddle.net/jezmck/2g9rbfnj/3/

**Comment by fergaldoyle** [comment]
This is expected in Vue. If you don't define your properties they won't be reactive.

**Comment by jezmck** [comment]
So you have the opportunity to be helpful by throwing an error, but don't want to?

**Comment by fergaldoyle** [comment]
It's not that I don't want to, it's just outside of the scope of this plugin. If you want messages to be thrown for undeclared `v-model` properties you should raise the suggestion on the Vue repo.
