### ISSUE TITLE
Custom component with Vue.js 2.5.2

### ISSUE THREAD

**Issue by sn0rcha** [fergaldoyle/vue-form#85]
Hey There,

Thanks for an awesome module. I upgraded my Vue today to 2.5.2 and for some reason my custom components are breaking when I'm passing the form state to the <validate :state="state"> component:

```<my-component :state="myFormState"></my-component>```
```[Vue warn]: Injection "vueFormState" not found```

Inside component:

```<template><div><validate :state="state"><input type="text" :value="value" name="'test'"></template>```

Any ideas why this would be?

**Comment by fergaldoyle** [comment]
Passing state down to a child component seems to work fine on 2.5.2:
https://jsfiddle.net/fergal_doyle/p2s5sxzd/
