### ISSUE TITLE
No validation when using component with directive

### ISSUE THREAD

**Issue by noscript** [fergaldoyle/vue-form#87]
Slightly modified the original jsfiddle from README https://jsfiddle.net/z9bmw7fh/

Changes:
* JAVASCRIPT
```diff
+Vue.directive('my-directive', {
+})
+
+Vue.component('my-input', {
+  template: '<input></input>'
+})
```
* HTML
```diff
-        <input type="text" name="name" class="form-control" required v-model.lazy="model.name" v-focus>
+        <input is="my-input" v-my-directive type="text" name="name" class="form-control" required v-model.lazy="model.name">
```

With these changes the "Name" input doesn't get validated. Removing either `is` attribute or directive makes it work again.

**Comment by fergaldoyle** [comment]
Fixed with https://github.com/fergaldoyle/vue-form/releases/tag/4.5.2
