### ISSUE TITLE
manually update formstate

### ISSUE THREAD

**Issue by JKHeadley** [fergaldoyle/vue-form#92]
Is it possible to manually update the formstate? For instance, I am trying to set `formstate.$dirty = true` based on an event, however it doesn't seem to work.

**Comment by fergaldoyle** [comment]
`formstate.$dirty` is like a computed property and cannot be manually changed. 

A form only becomes dirty when a child form field becomes dirty.  You could have a dummy field which you set dirty on the event, e.g.

```html
<validate class="hide"><input type="text" v-model="dummyValue" name="dummyField" /></validate>
```
```javascript
// on event:
formstate.dummyField._setDirty();
```

**Comment by JKHeadley** [comment]
This worked great, thanks!
