### ISSUE TITLE
Expressions for showing messages don't support more complex scenarios using parentheses

### ISSUE THREAD

**Issue by scottadamsmith** [fergaldoyle/vue-form#95]
I updated one of your jsfiddle examples to show the scenario I am referring to. 

https://jsfiddle.net/zfqt4yhq/131/

If you remove the parentheses from the showMessages option, it works. But as far as I can tell, parentheses should be supported as they work when used directly via the directives.

At first I thought this was limited to the config option, but then realized that the show-messages prop on the vue-form component and the show prop on the field-messages component also seem to go through the same expression evaluation. I think it's possible it also doesn't support using && and || in the same expression, but I could be wrong there. If this is accurate, this likely seems more like a feature request than a bug as I don't think your examples include those scenarios.

**Comment by fergaldoyle** [comment]
The `show` prop only accepts very simple expressions. It's not a directive which can accept any javascript expression.

You'll want to use scoped templates for complex if statements: 
https://github.com/fergaldoyle/vue-form#displaying-messages

**Comment by scottadamsmith** [comment]
Yeah, I think I started to figure out that I was confusing the v-if scenarios with the built-in expressions. Do you think this would be a beneficial addition to the library? If so, it might something I'd naively volunteer to add knowing it may be far more difficult that I am anticipating.

I was able to accomplish what I needed to by abandoning the use of the state and using the CSS classes for the states instead. This allowed for me to handle a more complex scenario, but doing so in a global manner so we don't have to specify it over and over in our app. That said, it was more difficult to do with CSS than it would have been using the actual states.

**Comment by fergaldoyle** [comment]
I initially implemented it like it currently is because I thought parsing complex expressions would be complex, but it turns out its easy.

You can now use expressions like `$focused && ($dirty || $submitted)` in the latest release.
