### ISSUE TITLE
Multiple Custom validators showing together

### ISSUE THREAD

**Issue by jonnycraze** [fergaldoyle/vue-form#96]
I have created a few custom validators that are used together on a component. The problem I've run into, is I'm seeing 2 errors at the same time, rather than just one.
```
validators: {
    'upload-file-required': (value, attrValue, vnode) => {
      return value.length ? true : false;
    },
    'upload-max-filesize': (value, attrValue, vnode) => {
      const maxFileSize = parseInt(attrValue);
      return vnode.componentInstance.lastUploadedFileSizeInBytes <= maxFileSize ? true : false;
    }
}
```

the component uses them like this:
```
<validate tag="label" class="upload-label" :class="{'dirty': uploadActionTaken}">
              <field-messages name="uploadfiles">
                <div slot="required" class="cb-secondary-message invalid">{{upload.validation.minFileCount.message}}</div>
                <div slot="upload-file-required" class="cb-secondary-message invalid">{{upload.validation.minFileCount.message}}</div>
                <div slot="upload-max-files" class="cb-secondary-message invalid">{{upload.validation.maxFileCount.message}}</div>
                <div slot="upload-max-filesize" class="cb-secondary-message invalid">{{upload.validation.maxFileSize.message}}</div>
                <div slot="upload-file-type" class="cb-secondary-message invalid">{{upload.validation.allowedFileTypes.message}}</div>
              </field-messages>
<div upload-file-required
                :upload-file-type="upload.validation.allowedFileTypes.value"
                :upload-max-filesize="upload.validation.maxFileSize.value"
                :upload-max-files="upload.validation.maxFileCount.value"
                @input="updateFiles"
                v-model="upload.files">
</div>
</validate>
```

**Comment by scottadamsmith** [comment]
I think this might have to do with this line of code:

https://github.com/fergaldoyle/vue-form/blob/5d892cc944e7951a99db7076d13e430b9785695c/src/components/validate.js#L183

In other spots in the library, we have special consideration for arrays, but if you initial value is an empty array, then this condition won't be met and will trigger all validations at once. I wonder if we need to add another part to the condition. Something like:

`|| (Array.isArray(value) && value.length === 0)`

I haven't considered it long enough to determine what side effects their might be for this behavior. Interested to hear your thoughts @fergaldoyle

**Comment by fergaldoyle** [comment]
If you have multiple validators then it is expected to see multiple error messages. The only exception is the `required` validator which will show by itself, and once it passes, will show any other validation messages. e.g.

I assume you want your `upload-file-required`  validator to act like the built in `required` validator. I could probably add a way to register custom validators to behave like a `required` validator.

But in your case you should be able to just use the `required` validator because it can handle arrays:
https://github.com/fergaldoyle/vue-form/blob/master/src/validators.js#L39
