### ISSUE TITLE
Submit does not wait for async validation to finish

### ISSUE THREAD

**Issue by Nickman87** [fergaldoyle/vue-form#97]
When I add an async validation, which takes a while to resolve, and then press submit while the validation is still pending, the form resolves to invalid instead of waiting for the validation to resolve.

Sample: https://jsfiddle.net/z7v141ug/

Expected behaviour:
While an async validation is still running, my submit callback is triggered after all promises are resolved to give a correct result.

**Comment by fergaldoyle** [comment]
Added this functionality with https://github.com/fergaldoyle/vue-form/releases/tag/4.7.1

**Comment by Nickman87** [comment]
Awesome! I'll try it out soon.
